#!/bin/sh

exec jsc -e '
//why does not utf-8 work?
//function utf_convert(fin) {
//	var	b1, b2,
//		fout = ""
//
//	for (var i = 0; i < fin.length; i++) {
//		b1 = fin.charCodeAt(i)
//		if (b1 >= 128) {
//			b2 = fin.charCodeAt(++i);
//			fout += String.fromCharCode(((b1 & 0x3f) << 6) + (b2 & 0x7f))
//		} else {
//			fout += fin[i]
//		}
//	}
//	return fout
//}

load("abc2svg-1.js")
load("cmdline.js")

function main(args) {
	if (!args[0]) {
		print("abcjsc-" + abc2svg.version + " " + abc2svg.vdate + " \n" +
		"	ABC to SVG translator\n" +
		"	Usage: abcjsc [options] ABC_file");
		quit()
	}
	abc_cmd("abcjsc", args, 0)
}

main(arguments)
' -- "$@"
